function data = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TESTINGEPOCFLEX1733542022 = IMPORTFILE(FILENAME) reads data from text
%  file FILENAME for the default selection.  Returns the data as a table.
%
%  TESTINGEPOCFLEX1733542022 = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  TestingEPOCFLEX1733542022 = importfile("/Users/alexandershaw/Documents/Testing_EPOCFLEX_173354_2022.12.19T10.54.41Z_intervalMarker.csv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 19-Dec-2022 11:39:19

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["latency", "duration", "type", "marker_value", "key", "timestamp", "marker_id"];
opts.VariableTypes = ["double", "double", "categorical", "categorical", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["type", "marker_value"], "EmptyFieldRule", "auto");

% Import the data
data = readtable(filename, opts);

end